# Generated by Django 5.1.1 on 2025-01-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0005_type_products_description_products_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='detail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
