# Generated by Django 5.1.1 on 2025-01-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0006_alter_products_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
